'use client'

import { useEffect, useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { CheckCircle2, Share2 } from 'lucide-react'
import Link from 'next/link'
import type { Protocol, ProtocolItem, Venue, Modality, ProtocolFormData } from '@/lib/types'
import { supabase } from '@/lib/supabase'
import { ModalityPill } from './ModalityPill'
// supabase import kept for weekly check-in fallback venue fetching
import WeeklyCheckin from './WeeklyCheckin'
import RecoveryScore from './RecoveryScore'
import ShareModal from './ShareModal'

// ─── Venue fetching ───────────────────────────────────────────────────────────

async function fetchVenueMatch(modalityKey: Modality, city: string): Promise<Venue | null> {
  const { data } = await supabase
    .from('venues')
    .select('*')
    .ilike('city', city)
    .contains('modalities', [modalityKey])
    .eq('is_featured', true)
    .limit(1)
    .single()
  return (data as Venue) ?? null
}

// ─── Animation variants ───────────────────────────────────────────────────────

const itemVariants = {
  hidden: { opacity: 0, y: 16 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.35, ease: [0.16, 1, 0.3, 1] as const },
  },
}

const containerVariants = {
  hidden: {},
  visible: {
    transition: { staggerChildren: 0.15 },
  },
}

// ─── Journey progress ─────────────────────────────────────────────────────────

function JourneyProgress({ weekNumber }: { weekNumber: number }) {
  const weeks = [1, 2, 3]
  return (
    <motion.div
      initial={{ opacity: 0, y: -8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4 }}
      className="flex items-center justify-center gap-3 mb-8"
    >
      <span className="text-recvr-muted text-xs font-mono tracking-widest uppercase">Your Recovery Journey</span>
      <div className="flex items-center gap-1.5">
        {weeks.map((w) => (
          <div key={w} className="flex items-center gap-1.5">
            <div
              className={`flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium transition-all ${
                w < weekNumber
                  ? 'bg-recvr-copper/20 text-recvr-copper border border-recvr-copper/40'
                  : w === weekNumber
                  ? 'bg-recvr-copper text-recvr-bg'
                  : 'bg-recvr-surface border border-recvr-border text-recvr-muted'
              }`}
            >
              {w < weekNumber && <CheckCircle2 className="w-3 h-3" />}
              Week {w}
            </div>
            {w < 3 && (
              <div className={`w-4 h-px ${w < weekNumber ? 'bg-recvr-copper/40' : 'bg-recvr-border'}`} />
            )}
          </div>
        ))}
      </div>
    </motion.div>
  )
}

// ─── Protocol item — document style ──────────────────────────────────────────

function ProtocolItemRow({
  item,
  city,
  preloadedVenue,
}: {
  item: ProtocolItem
  city: string
  preloadedVenue?: Venue | null
}) {
  // Use pre-loaded venue if available (week 1 from ProtocolSection pre-fetch).
  // Fall back to on-demand fetch for week 2/3 generated by WeeklyCheckin.
  const [venue, setVenue] = useState<Venue | null>(preloadedVenue ?? null)

  useEffect(() => {
    if (preloadedVenue !== undefined) return // already have it
    fetchVenueMatch(item.venue_modality_match, city).then(setVenue)
  }, [item.venue_modality_match, city, preloadedVenue])

  return (
    <div
      className="
        sm:bg-transparent sm:border-0 sm:rounded-none sm:p-0
        bg-recvr-surface border border-recvr-border rounded-lg p-4
      "
    >
      {/* Day label */}
      <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-recvr-copper mb-3">
        Day {item.day}
      </p>

      {/* Modality + duration + price — single row */}
      <div className="flex items-baseline gap-4 flex-wrap mb-2">
        <span className="text-[18px] font-medium text-recvr-text leading-tight">
          {item.modality}
        </span>
        <span className="font-mono text-[13px] text-recvr-text-secondary">
          {item.duration_minutes} min
        </span>
        <span className="font-mono text-[13px] text-recvr-copper">
          From £{item.price_from}
        </span>
      </div>

      {/* Venue line */}
      {venue ? (
        <div className="flex items-center justify-between mb-4">
          <span className="text-[13px] text-recvr-text-secondary">
            {venue.name}
            <span className="text-recvr-text-muted mx-1.5">·</span>
            {venue.city}
          </span>
          <Link
            href={`/venues/${venue.slug}`}
            className="text-[13px] text-recvr-copper hover:text-recvr-copper-light transition-colors duration-150"
          >
            View venue →
          </Link>
        </div>
      ) : (
        <div className="mb-4">
          <Link
            href={`/venues?modality=${item.venue_modality_match}&city=${encodeURIComponent(city)}`}
            className="text-[13px] text-recvr-text-muted hover:text-recvr-text transition-colors duration-150"
          >
            Search venues near you →
          </Link>
        </div>
      )}

      {/* Modality pill */}
      <div className="mb-4">
        <ModalityPill modality={item.modality_key} size="sm" />
      </div>

      {/* Physiological reason */}
      <p className="text-[15px] text-recvr-text-secondary leading-relaxed max-w-[600px]">
        {item.reason}
      </p>

      {/* Not-instead-of — subtle footnote */}
      {item.not_instead_of && (
        <p className="mt-3 text-[12px] text-recvr-text-muted italic leading-relaxed max-w-[560px]">
          Not instead of: {item.not_instead_of}
        </p>
      )}
    </div>
  )
}

// ─── Email capture ────────────────────────────────────────────────────────────

function EmailCapture({ summary, city }: { summary: string; city: string }) {
  const [email, setEmail] = useState('')
  const [status, setStatus] = useState<'idle' | 'loading' | 'done' | 'error'>('idle')

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    if (!email.includes('@')) return
    setStatus('loading')
    try {
      const res = await fetch('/api/capture-email', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, protocol_summary: summary, city, source: 'protocol_output' }),
      })
      if (!res.ok) throw new Error('Failed')
      setStatus('done')
    } catch {
      setStatus('error')
    }
  }

  return (
    <div>
      <p className="font-mono text-[11px] uppercase tracking-[0.08em] text-recvr-text-secondary mb-4">
        Get this protocol by email
      </p>
      {status === 'done' ? (
        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          className="text-[14px] text-recvr-success"
        >
          Sent. Check your inbox.
        </motion.p>
      ) : (
        <>
          <form onSubmit={handleSubmit} className="flex gap-3 max-w-[420px]">
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="Your email"
              required
              className="flex-1 bg-recvr-surface border border-recvr-border rounded-md px-3 py-2
                         text-[14px] text-recvr-text placeholder:text-recvr-text-muted
                         focus:outline-none focus:border-recvr-border-active transition-colors"
            />
            <button
              type="submit"
              disabled={status === 'loading'}
              className="px-4 py-2 bg-recvr-copper hover:bg-recvr-copper-light text-white
                         rounded-md text-[13px] font-medium transition-colors duration-150 whitespace-nowrap
                         disabled:opacity-60"
            >
              {status === 'loading' ? 'Sending…' : 'Send it →'}
            </button>
          </form>
          {status === 'error' && (
            <p className="text-red-400 text-[12px] mt-2">Something went wrong. Try again.</p>
          )}
        </>
      )}
    </div>
  )
}

// ─── Main export ──────────────────────────────────────────────────────────────

export default function ProtocolOutput({
  protocol,
  matchedVenues = {},
  city,
  formData,
  onReset,
}: {
  protocol: Protocol
  matchedVenues?: Record<number, Venue | null>
  city: string
  formData: ProtocolFormData
  onReset: () => void
}) {
  const [displayedProtocol, setDisplayedProtocol] = useState<Protocol>(protocol)
  const [weekNumber, setWeekNumber] = useState(1)
  const [lastResponse, setLastResponse] = useState<string | undefined>(undefined)
  const [currentIssues, setCurrentIssues] = useState<string[]>(formData.issues)
  const [shareOpen, setShareOpen] = useState(false)
  const { hasEvent, eventDate } = formData

  const handleNewProtocol = (newProtocol: Protocol, response?: string, newIssues?: string[]) => {
    setDisplayedProtocol(newProtocol)
    setWeekNumber((w) => w + 1)
    if (response) setLastResponse(response)
    if (newIssues && newIssues.length > 0) setCurrentIssues(newIssues)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }

  return (
    <div className="w-full max-w-[720px] mx-auto">

      {/* Recovery Readiness Score */}
      <RecoveryScore
        input={{
          trainingLoad: formData.trainingLoad,
          issues: currentIssues,
          previousResponse: lastResponse,
        }}
      />

      {/* Journey progress */}
      <JourneyProgress weekNumber={weekNumber} />

      {/* Race countdown banner */}
      {hasEvent && eventDate && (
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
          className="flex items-center justify-between px-4 py-3 rounded-xl border border-recvr-copper/20 bg-recvr-copper/5 mb-6"
        >
          <div className="flex items-center gap-3">
            <div className="w-2 h-2 rounded-full bg-recvr-copper animate-pulse" />
            <span className="text-sm text-recvr-text font-medium">Race countdown active</span>
          </div>
          <span className="text-sm font-mono text-recvr-copper">
            {Math.ceil(
              (new Date(eventDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24 * 7)
            )}{' '}
            weeks to race day
          </span>
        </motion.div>
      )}

      {/* Header */}
      <AnimatePresence mode="wait">
        <motion.div
          key={`header-week-${weekNumber}`}
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.4 }}
          className="mb-8"
        >
          <p className="font-mono text-[11px] uppercase tracking-[0.1em] text-recvr-copper mb-4">
            Week {weekNumber} — 7-Day Recovery Protocol
          </p>
          <p className="font-tiempos font-light italic text-[22px] md:text-[24px] leading-snug text-recvr-text">
            {displayedProtocol.summary}
          </p>
        </motion.div>
      </AnimatePresence>

      {/* Top divider */}
      <div className="border-t border-recvr-border mb-8" />

      {/* Protocol items — document style */}
      <AnimatePresence mode="wait">
        <motion.div
          key={`items-week-${weekNumber}`}
          variants={containerVariants}
          initial="hidden"
          animate="visible"
        >
          {displayedProtocol.protocol.map((item, index) => (
            <motion.div key={`${item.day}-${item.modality_key}-w${weekNumber}`} variants={itemVariants}>
              <ProtocolItemRow
                item={item}
                city={city}
                preloadedVenue={matchedVenues[item.day]}
              />
              {index < displayedProtocol.protocol.length - 1 && (
                <div className="border-t border-recvr-border my-8" />
              )}
            </motion.div>
          ))}
        </motion.div>
      </AnimatePresence>

      {/* Bottom divider */}
      <div className="border-t border-recvr-border mt-8 mb-10" />

      {/* Share button */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, delay: 0.2 }}
        className="mb-8"
      >
        <button
          onClick={() => setShareOpen(true)}
          className="inline-flex items-center gap-2 px-5 py-2.5 rounded-full border border-recvr-border text-recvr-muted hover:border-recvr-copper/50 hover:text-recvr-text transition-colors text-sm"
        >
          <Share2 className="w-4 h-4" />
          Share this programme
        </button>
      </motion.div>

      {/* Email capture */}
      <div className="mb-10">
        <EmailCapture summary={displayedProtocol.summary} city={city} />
      </div>

      {/* Weekly check-in — only show for weeks 1 & 2 */}
      {weekNumber < 3 && (
        <WeeklyCheckin
          formData={formData}
          currentProtocol={displayedProtocol}
          weekNumber={weekNumber}
          currentIssues={currentIssues}
          onNewProtocol={handleNewProtocol}
        />
      )}

      {/* Reset */}
      <div className="mt-8 mb-4">
        <button
          onClick={onReset}
          className="text-[13px] text-recvr-text-secondary hover:text-recvr-text transition-colors duration-150"
        >
          ← Generate a new protocol
        </button>
      </div>

      {/* Share modal */}
      <ShareModal
        isOpen={shareOpen}
        onClose={() => setShareOpen(false)}
        protocol={displayedProtocol}
        formData={formData}
      />
    </div>
  )
}
